apiVersion: v1
kind: ConfigMap
metadata:
  name: geth-config
  namespace: local-setup
data:
  etherbase: {{ .etherbase }}
  genesis.json: |
    {
      "config": {
        "chainId": 1101,
        "homesteadBlock": 0,
        "byzantiumBlock": 0,
        "constantinopleBlock": 0,
        "petersburgBlock": 0,
        "istanbulBlock": 0,
        "eip150Block": 0,
        "eip155Block": 0,
        "eip158Block": 0
      },
      "difficulty": "0x20",
      "gasLimit": "0x493E0000",
      "alloc": {
        {{- range $index, $address := .addresses }}
        {{- if $index}},{{end}}
        "{{$address}}": {
          "balance": "1000000000000000000000000000000000000000000000000000000"
        }
        {{- end }}
      }
    }