name: e2e summary

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: installing JSON processor - jq
          run: sudo apt-get install jq

        - name: Setting up git config
          run: |
            git config --local user.email "cron-e2e-summary@github.com"
            git config --local user.name ${{github.actor}}
        
        - name: Updating tbtc.js version
          run: |
            cd e2e
            jq '.dependencies."@keep-network/tbtc.js" = "0.18.0-rc.1"' \
            package.json > package.json.tmp && mv package.json.tmp package.json
        - name: Installing npm dependencies
          run: cd e2e && npm install
        
        - name: Running e2e summary test 
          run: | 
            cd e2e
            node --experimental-json-modules e2e-summary.js \
            --bitcoin-electrum-host 34.70.251.19 \
            --bitcoin-electrum-port 8080 \
            --bitcoin-network testnet \
            --blocks-timespan 7500 \
            --ethereum-node wss://ropsten.infura.io/ws/v3/894b9437c4e04c28bd9a04053c567b27 \
            --ethereum-pk f95e1da038f1fd240cb0c966d8826fb5c0369407f76f34736a5c381da7ca0ecd

        - name: Deploy e2e summary site
          run: |
            git commit e2e/site/index.html -m "Updating e2e summary page" || echo "No changes to commit"
            git push --force "https://${{github.actor}}:${{secrets.Token}}@github.com/${{github.repository}}.git"